FROM python:3.12-slim-bookworm

WORKDIR /workdir

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY /backend/api backend/api

CMD ["uvicorn", "backend.api.main:app", "--host", "0.0.0.0", "--port", "8000"]