services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./frontend:/var/www/frontend
    depends_on:
      - api
      - frontend
    networks:
      - def_net

  certbot:
    image: certbot/certbot
    container_name: visitka-certbot
    restart: unless-stopped
    networks:
      - def_net
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      - nginx
    entrypoint: >
      sh -c "trap exit TERM;
      # Автообновление каждые 12 часов
      while :;
      do
        certbot renew --webroot --webroot-path=/var/www/certbot;
        sleep 12h & wait $${!};
      done;"
    

  db:
    image: postgres:latest
    env_file: '.env'
    ports:
      - '5431:5432'
    networks:
      - def_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ldev -d visitka" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ${PWD}/volumes/postgres:/var/lib/postgresql/18/docker

  api:
    image: api:latest
    build: 
      context: .
      dockerfile: Dockerfile.api
    env_file: '.env'
    networks:
      - def_net
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    networks:
      - def_net
    restart: unless-stopped
  
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telegram_bot
    restart: unless-stopped
    env_file:
      - .env


networks:
  def_net:
    driver: bridge
